baseURL = "https://example.com" # TODO
title = "Anya Walsh"
author = "Anya Walsh"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = [] # ['blog']

  googleFonts = false

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Anya Walsh"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Anya Walsh"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Anya Walsh -  Temple Priestess, Sacred Sexuality, Somatic Embodiment & Women's work facilitator, Vocal Star Reiki Healer, Yoga Teacher, Ceremonial Dancer, Ceremonial Vocalist and Artist"
    meta_og_title = "Anya Walsh"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev" # TODO
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png" # TODO
    meta_og_description = "Anya Walsh -  Temple Priestess, Sacred Sexuality, Somatic Embodiment & Women's work facilitator, Vocal Star Reiki Healer, Yoga Teacher, Ceremonial Dancer, Ceremonial Vocalist and Artist."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username" # TODO
    meta_twitter_creator = "@username" # TODO

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/niccokunzmann/somarosa.co.uk"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 10

  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/somarosa.sensual/"
    pre = "<i class='fa-brands fa-instagram'></i>"
      weight = 2

  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/HeartoftheroseWales"
    pre = "<i class='icon-facebook text-2xl'></i>"
      weight = 3

  [[menu.footer]]
    name = "Email"
    url = "mailto:heartoftherosewales@gmail.com"
    pre = "<i class='icon-email text-2xl'></i>"
      weight = 4

